### ISSUE TITLE
Handling the application errors if there is no repository connection

### ISSUE THREAD

**Issue by DorukAkinci** [meshcloud/unipipe-service-broker#37]
If the OSB application throws an error on the terraform resource creation phase, terraform states that the resource is failed. 

It happens if there is no catalog.yml file in the Github Repo or the Deploy keys are not initialized yet. 

If we can somehow handle the errors without crashing the app, we could create better automations. 

`2021-06-16T09:55:24.765261Zorg.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'genericCatalogService' defined in URL [jar:file:/app/generic-osb-api-1.0.0.jar!/BOOT-INF/classes!/io/meshcloud/dockerosb/service/GenericCatalogService.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'gitOperationContextFactory' defined in URL [jar:file:/app/generic-osb-api-1.0.0.jar!/BOOT-INF/classes!/io/meshcloud/dockerosb/persistence/GitOperationContextFactory.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'gitHandlerService' defined in URL [jar:file:/app/generic-osb-api-1.0.0.jar!/BOOT-INF/classes!/io/meshcloud/dockerosb/persistence/GitHandlerService.class]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [io.meshcloud.dockerosb.persistence.GitHandlerService]: Constructor threw exception; nested exception is org.eclipse.jgit.api.errors.InvalidRemoteException: Invalid remote: origin at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:797) ~[spring-beans-5.2.7.RELEASE.jar!/:5.2.7.RELEASE] at `

**Comment by JohannesRudolph** [comment]
Do you have a preference on what the service broker behavior should be in that case? Return a 503 until a catalog is provided? How would the operator notice that? 

At the moment I think it's somewhat reasonable to fail the OSB startup and provide an exception in the logs. I'd assume this would only happen on the first deploy or when an operator changes something about the configuration, in which case someone is babysitting the deployment anyway. So letting the deployment fail (service won't come up) seems to be a good solution IMHO. 

In case there's nothing more sensibly printed to the logs you have a very good point though, there needs to be a clear message that the catalog is missing and what an operator needs to do to fix this.
