### ISSUE TITLE
RFC: Enable unipipe-cli to perform common git interactions

### ISSUE THREAD

**Issue by JohannesRudolph** [meshcloud/unipipe-service-broker#47]
When implementing GitOps pipelines there are a few common challenges that service operators need to solve in their interaction with git. We should consider the potential that of including some of them in the scope of unipipe-cli.

**Rebase/Merge Loops**
There is always contention around usage of the shared git repository between the CI/CD pipeline (e.g. writing IaC files, status.yml files) and the service broker (writing new instance.yml files). While by design these changes should always merge cleanly, the CI/CD pipeline still needs to find a way to reliably push any changes made locally back to the origin repository.

There are various ways of solving this and we use variations of those already in the field
- pull requests: let the CI/CD pipeline create PRs and let a tool like GitHub (or a bot like kodiak/prowbot etc.) handle their merging
- rebase loops: push changes to the remote and if it fails rebase and retry until success, e.g. in a bash loop

**Leverage git ls-files**
At the moment unipipe-cli naively iterates files and directories using system calls. This works, but it can potentially be made faster if we use `git ls-files` instead, which can leverage internal data structures like index files to quickly produce file lists.

**Common git commands**
There a few common git commands that operators repeatedly need to work with service instances, e.g. listing commits with changes to a specific file/service instance directory. None of those operations is unipipe specific and typically it's very easy to figure out with a decent git gui tool, reading the git man pages or googling it. However, it may be helpful if we can help operators discover/generate those common git commands.

**Comment by felixzieger** [comment]
Basic git support for pull/pushing has been implemented in https://github.com/meshcloud/unipipe-service-broker/blob/master/CHANGELOG.md#v173
