### ISSUE TITLE
Enable APIs automatically during unipipe deployment

### ISSUE THREAD

**Issue by malhussan** [meshcloud/unipipe-service-broker#59]
While running terraform with `create_cloudrun_service` set to `false`, I got:

![image](https://user-images.githubusercontent.com/30862222/147548738-e9a005e1-9626-4127-b01d-84b4cf80cedb.png)

after enabling it, and then going through the steps and setting the same variable to `true`, I got:

![image](https://user-images.githubusercontent.com/30862222/147548859-86786f2f-577a-48fb-bdaa-24d63faa9807.png)

Deployment experience would be smoother if they were enabled automatically.

**Comment by DorukAkinci** [comment]
Yes, you are right! I also experienced the same thing when i tried that deployment last time. It seems that is also possible. I will create list of services which are required and add smth like this into terraform template.

```
variable "gcp_service_list" {
  description ="The list of apis necessary for the project"
  type = list(string)
  default = [
    "container.googleapis.com",
    "run.googleapis.com"
  ]
}

resource "google_project_service" "gcp_services" {
  for_each = toset(var.gcp_service_list)
  project = "var.PROJECT-ID"
  service = each.key
}
```
