### ISSUE TITLE
Inconsistent naming of GIT_SSH_KEY environment variable

### ISSUE THREAD

**Issue by DatMicha** [meshcloud/unipipe-service-broker#71]
https://github.com/meshcloud/unipipe-service-broker/wiki/Reference#configuration-reference claims the environent variable for the ssh key is named GIT_SSH-KEY instead of GIT_SSH_KEY, which is being used in other wiki articles and as far as I can tell in the code.

**Comment by JohannesRudolph** [comment]
Hi @DatMicha thanks for reporting this. The reference deployments you can generate with `unipipe generate unipipe-service-broker-deployment` do indeed use the snake-case (all upper) so `GIT_SSH_KEY`.

However, `GIT_SSH-KEY` will also work thanks to spring's relaxed property binding that the broker uses to load the configuration, see https://docs.spring.io/spring-boot/docs/current/reference/html/features.html#features.external-config.typesafe-configuration-properties.relaxed-binding

I agree though that we should make the documentation more consistent with the templates here.

**Comment by felixzieger** [comment]
Thanks for reporting! 

I adapted the Wiki accordingly. I could not find any other inconsistencies and will close the issue.
